name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Composer update
      run: composer update

    - name: Composer install
      run: composer install
  test:
    steps:
    - name: Testing
      run: php bin/phpunit


